const projectsData = [
  {
    id: "s5df456s4fds564f",
    projectName: "Let's Talk School",
    websiteImage: "https://i.ibb.co/WBCVcB2/Screenshot-31.png",
    githubLink: "https://github.com/Bulbulahmed10/lets-talk-mern-client",
    liveSiteLink: "https://lets-talk-school-35e1a.web.app/",
  },
  {
    id: "ds6gf76dsf7ds687f",
    projectName: "Chefscout",
    websiteImage: "https://i.ibb.co/BB6m8Lg/Screenshot-32.png",
    githubLink: "https://github.com/Bulbulahmed10/chefscout-mern-firebase",
    liveSiteLink: "https://chefscout-client-assignment.web.app/",
  },
  {
    id: "dgdfs5d64f6ds4f5d",
    projectName: "Toyland",
    websiteImage: "https://i.ibb.co/hD9YrwS/Screenshot-33.png",
    githubLink: "https://github.com/Bulbulahmed10/toyland-mern",
    liveSiteLink: "https://toyland-dc9cf.web.app/",
  },
  {
    id: "fsd6f7ds6f41ds56445",
    projectName: "Programming Hero",
    websiteImage: "https://i.ibb.co/G9RVjjR/Screenshot-34.png",
    githubLink: "https://github.com/Bulbulahmed10/programming-hero-website",
    liveSiteLink: "https://programming-hero-website.netlify.app/",
  },
  {
    id: "6dsf4d61s4fds654f",
    projectName: "Ahmed Shop",
    websiteImage: "https://i.ibb.co/qgLXhXj/ahmed-store.png",
    githubLink: "https://github.com/Bulbulahmed10/react-fake-store.git",
    liveSiteLink: "https://ahmed-store-bd.netlify.app/",
  },
  {
    id: "d64sd6f45d4f5d4fd",
    projectName: "Advice Generator",
    websiteImage: "https://i.ibb.co/nbgg1Mb/advice-generator.png",
    githubLink: "https://github.com/Bulbulahmed10/advice-generator-app.git",
    liveSiteLink: "https://bulbu-ahmed-advice-generator.netlify.app/",
  },
  {
    id: "d6sf5sd416fsd784d",
    projectName: "Tasty Hut",
    websiteImage: "https://i.ibb.co/02mdkPS/tasty-hut.png",
    githubLink: "https://github.com/Bulbulahmed10/tasty-hut.git",
    liveSiteLink: "https://teasty-hut.netlify.app/",
  },
  {
    id: "re45sd4f56ds4fs56d4",
    projectName: "Aden E-commerce",
    websiteImage: "https://i.ibb.co/6wFbbX3/aden.png",
    githubLink: "https://github.com/Bulbulahmed10/aden---Ecommerce-website.git",
    liveSiteLink: "https://aden-ecommerce-webiste.netlify.app/",
  },
  {
    id: "df646gbfdg65d4fg56fd4",
    projectName: "Legal Solutions",
    websiteImage: "https://i.ibb.co/FgYYMys/legal-solution.png",
    githubLink: "https://github.com/Bulbulahmed10/legal-solution.git",
    liveSiteLink: "https://legal-solution-house.netlify.app/",
  },
  {
    id: "g46er8r7tr54f5g4d",
    projectName: "Tea House",
    websiteImage: "https://i.ibb.co/9V0Tg0F/tea-house.png",
    githubLink: "https://github.com/Bulbulahmed10/tea-house-website.git",
    liveSiteLink: "https://bulbulahmed10.github.io/tea-house-website/",
  },
  {
    id: "45g6d4fg567s4df78d",
    projectName: "Convention Center",
    websiteImage: "https://i.ibb.co/2tsQkC4/convention-center.png",
    githubLink: "https://github.com/Bulbulahmed10/convention-center.git",
    liveSiteLink: "https://bulbulahmed10.github.io/convention-center/",
  },
  {
    id: "sg4f89d7fds8f4d5",
    projectName: "G3 Architects",
    websiteImage: "https://i.ibb.co/N7N0c7S/g3-architects.png",
    githubLink: "https://github.com/Bulbulahmed10/G3-Architects.git",
    liveSiteLink: "https://bulbulahmed10.github.io/G3-Architects/",
  },
  {
    id: "sg4f89d7fds8f4d5",
    projectName: "Influencer Gears",
    websiteImage: "https://i.ibb.co/rKB8xtL/influencer-gears.png",
    githubLink: "https://github.com/Bulbulahmed10/influencer-gears.git",
    liveSiteLink: "https://bulbulahmed10.github.io/influencer-gears/",
  },
  {
    id: "5465ds4fs56d4f6ds5",
    projectName: "Leader board",
    websiteImage: "https://i.ibb.co/86F0dPs/leaderboard.png",
    githubLink: "https://github.com/Bulbulahmed10/leaderboard-website.git",
    liveSiteLink: "https://bulbulahmed10.github.io/leaderboard-website/",
  },
  {
    id: "564s65f4ds67r845d4fd",
    projectName: "Heart Animation",
    websiteImage: "https://i.ibb.co/smrt9Jz/heart-animation.png",
    githubLink:
      "https://github.com/Bulbulahmed10/heart-symobl-animation-css.git",
    liveSiteLink: "https://bulbulahmed10.github.io/heart-symobl-animation-css/",
  },
  {
    id: "ks5ds7fgs6df4fd5sf454",
    projectName: "Dev Portfolio",
    websiteImage: "https://i.ibb.co/sQm7sg1/dev-protfolio.png",
    githubLink: "https://github.com/Bulbulahmed10/dev-portfolio-website.git",
    liveSiteLink: "https://bulbulahmed10.github.io/dev-portfolio-website/",
  },
  {
    id: "5s64fd5s64fds54fds6",
    projectName: "Donate Today",
    websiteImage: "https://i.ibb.co/P9wS2HJ/donate-tody.png",
    githubLink: "https://github.com/Bulbulahmed10/donate-today-website.git",
    liveSiteLink: "https://bulbulahmed10.github.io/donate-today-website/",
  },
  {
    id: "55sd64f5ds64fds45ds",
    projectName: "New Year",
    websiteImage: "https://i.ibb.co/Sc9JLRj/new-year.png",
    githubLink: "https://github.com/Bulbulahmed10/new-year-new-me-website.git",
    liveSiteLink: "https://bulbulahmed10.github.io/new-year-new-me-website/",
  },
];

export default projectsData
